/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/flowgrid/protocol/cgo */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 4 "bridge.go"

#include <stdlib.h>
#include <stdint.h>

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern uint8_t* fg_frame_encode(uint8_t frameType, uint16_t sequence, uint64_t timestamp, uint8_t* payload, uint8_t payloadLen, size_t* outLen);
extern int fg_frame_decode(uint8_t* data, size_t len, uint8_t* outType, uint16_t* outSeq, uint64_t* outTs, uint8_t* outPayloadLen, uint8_t** outPayload);
extern uint8_t* fg_frame_encode_with_hmac(uint8_t frameType, uint16_t sequence, uint64_t timestamp, uint8_t* payload, uint8_t payloadLen, uint8_t* hmacKey, size_t hmacKeyLen, size_t* outLen);
extern int fg_frame_decode_with_hmac(uint8_t* data, size_t len, uint8_t* hmacKey, size_t hmacKeyLen, uint8_t* outType, uint16_t* outSeq, uint64_t* outTs, uint8_t* outPayloadLen, uint8_t** outPayload);
extern int fg_frame_validate(uint8_t frameType, uint16_t sequence, uint64_t timestamp, uint8_t payloadLen, uint8_t* payload);
extern uint8_t* fg_payload_keydown(uint16_t keyCode, uint8_t modifiers, size_t* outLen);
extern uint8_t* fg_payload_keyup(uint16_t keyCode, size_t* outLen);
extern uint8_t* fg_payload_mousemove(int16_t deltaX, int16_t deltaY, size_t* outLen);
extern uint8_t* fg_payload_mousebtn(uint8_t buttonID, uint8_t state, size_t* outLen);
extern uint8_t* fg_payload_scroll(int16_t deltaY, int16_t deltaX, size_t* outLen);
extern uint8_t* fg_payload_latency_ping(uint64_t timestamp, size_t* outLen);
extern uint8_t* fg_payload_latency_pong(uint64_t timestamp, size_t* outLen);
extern uint8_t* fg_payload_disconnect(uint8_t reason, size_t* outLen);
extern uint8_t* fg_payload_error(uint8_t code, char* msg, size_t* outLen);
extern int fg_payload_unmarshal_keydown(uint8_t* data, size_t len, uint16_t* outKeyCode, uint8_t* outModifiers);
extern int fg_payload_unmarshal_keyup(uint8_t* data, size_t len, uint16_t* outKeyCode);
extern int fg_payload_unmarshal_mousemove(uint8_t* data, size_t len, int16_t* outDX, int16_t* outDY);
extern int fg_payload_unmarshal_mousebtn(uint8_t* data, size_t len, uint8_t* outBtn, uint8_t* outState);
extern int fg_payload_unmarshal_scroll(uint8_t* data, size_t len, int16_t* outDY, int16_t* outDX);
extern int fg_payload_unmarshal_disconnect(uint8_t* data, size_t len, uint8_t* outReason);
extern void* fg_keymap_load_file(char* path, char** outVersion, size_t* outRuleCount);
extern int fg_keymap_lookup(void* handle, uint8_t fromPlatform, uint8_t toPlatform, uint16_t keyCode, uint8_t modifiers, char* context, uint16_t* outKeyCode, uint8_t* outModifiers, int* outFound);
extern uint8_t fg_remap_modifiers(uint8_t mods, uint8_t fromPlatform, uint8_t toPlatform);
extern void fg_keymap_free(void* handle);
extern void fg_keymap_free_string(char* s);
extern void fg_free_buffer(void* buf);
extern uint8_t* fg_ble_advertising_encode(uint8_t protocolVer, uint8_t platform, uint8_t caps, uint16_t wifiChan, size_t* outLen);
extern int fg_ble_advertising_decode(uint8_t* data, size_t len, uint8_t* outVer, uint8_t* outPlatform, uint8_t* outCaps, uint16_t* outChan);
extern int fg_classify_rssi(int rssi);
extern uint8_t* fg_wifidirect_request_encode(uint8_t version, uint16_t port, uint8_t* ipAddr, uint8_t* subnet, uint8_t channel, uint8_t band, uint8_t security, uint8_t* pskHash, size_t* outLen);
extern uint8_t* fg_wifidirect_response_encode(uint8_t version, uint8_t status, uint16_t port, uint16_t channel, uint8_t band, size_t* outLen);
extern GoUintptr fg_latency_monitor_new(int maxSamples);
extern void fg_latency_record_ping(GoUintptr id, uint64_t sendTimeUs);
extern int fg_latency_record_pong(GoUintptr id, uint64_t pongTimestampUs, uint64_t nowUs, double* outMs, double* outJitter);
extern int fg_latency_latest(GoUintptr id, double* outMs, double* outJitter, int* outQuality);
extern int fg_latency_stats(GoUintptr id, double* outMin, double* outMax, double* outAvg);
extern void fg_latency_monitor_free(GoUintptr id);
extern GoUintptr fg_heartbeat_tracker_new(void);
extern void fg_heartbeat_received(GoUintptr id);
extern int fg_heartbeat_tick(GoUintptr id);
extern void fg_heartbeat_tracker_free(GoUintptr id);
extern GoUintptr fg_reconnect_state_new(void);
extern void fg_reconnect_start(GoUintptr id, uint64_t* outBackoffMs, int* outOK);
extern void fg_reconnect_set_connected(GoUintptr id);
extern void fg_reconnect_reset(GoUintptr id);
extern void fg_reconnect_state_free(GoUintptr id);
extern GoUintptr fg_sequence_tracker_new(uint32_t seqInit);
extern uint16_t fg_sequence_next(GoUintptr id);
extern int fg_sequence_check(GoUintptr id, uint16_t received);
extern void fg_sequence_reset(GoUintptr id, uint32_t seqInit);
extern void fg_sequence_tracker_free(GoUintptr id);
extern GoUintptr fg_fragment_reassembler_new(void);
extern int fg_fragment_feed(GoUintptr id, uint8_t* data, size_t dataLen, size_t* outLen, uint8_t** outData);
extern void fg_fragment_cleanup(GoUintptr id);
extern void fg_fragment_reassembler_free(GoUintptr id);
extern char* fg_error_string(uint8_t code);
extern uint8_t* fg_identify_payload_encode(uint8_t version, uint8_t platform, uint8_t role, uint8_t caps, uint32_t seqInit, char* name, size_t* outLen);
extern uint8_t* fg_identify_response_encode(uint8_t status, uint8_t platform, uint8_t caps, char* name, size_t* outLen);

#ifdef __cplusplus
}
#endif
